In [20]:
import numpy as np
import math
import scipy.linalg as la
import itertools

# Semana 2 PIBIC

## Gerando Tabelas Verdade (Truth Tables)

Para a geração de tabelas verdade com n inputs no circuito, com $n \ge 1$. Esta é uma função que gera uma tabela verdade em forma de matriz para n inputs arbitrários.

Além disso, modifiquei-a para que retornasse um numpy array ao invés de um array convencional do python, aumentando a eficiência da função visto que numpy arrays são mais rápidos de se fazer modificações na função e até mesmo posteriores.

In [21]:
def Tv(NumberOfInputs):
    """
    Retorna uma tabela verdade (TruthTable) dado um circuito com n inputs maiores ou iguais a 1
    Checa se a variável NumberOfInputs é inteira. Se sim, continua normalmente, se não lança uma exceção com a mensagem
    'Parameter \'NumberOfInputs\' must be a integer'

    Parâmetros
    ------------------------------------------------
    :param NumberOfInputs: número de inputs do circuito lógico, deve ser um número inteiro (obrigatoriamente)
    
    Retorno
    ------------------------------------------------
    :return: Retorna a tabela verdade como uma lista do Python (caso necessário, transformar o retorno em numpy array)
    """
    if not isinstance(NumberOfInputs, int):
        raise ValueError('Parameter \'NumerOfInputs\' must be a integer')
    if NumberOfInputs < 1:                                                   
        raise ValueError('Parameter \'NumberOfInputs\' must be greater or equal to 1')
    else:
        table = list(itertools.product ([0, 1], repeat = NumberOfInputs))    
        table = np.array(table, dtype=float)
        return table

In [22]:
Table = Tv(3)
Table
# try...catch

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 1.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

Uma verificação necessária nessa função se dá no momento da passagem do argumento $NumberOfInputs$. Se o número passado não for um inteiro, a função retorna um erro e não continua seus cálculos.

Além disso, caso o argumento de número de inputs for menor do que 1, a função retorna um erro de valor de parâmetro (ValueError).

A função $Tv$ retorna uma tabela verdade como numpy array de acordo com o número de inputs do circuito e com valores da tabela verdade do tipo float para não resultar em erros de truncamento no cálculo do epsilon.

## Modulação PAM

Quando tratamos de tabelas verdade de circuitos eletrônicos, muitas vezes precisamos converter esses sinais em Modulação por Amplitude do Pulso (PAM: Pulse Amplitude Moduling) para realizarmos cálculos ou verificações e depois retornamos a representação do circuito a meneira original, com 0's e 1's.

Para isso, convertemos os campos (labels) das tabelas verdades por $1+\epsilon$ caso o valor no campo seja 1 ou $1-\epsilon$ caso seja 0. A matriz resultante é chamada de $\textbf{Inp}$.

In [23]:
def PAM(TruthTable, epsilon):
    """
    Função que retorna uma modulação PAM para uma dada tabela verdade (TruthTable) e certo epsilon real arbitrário.
    Não modifica a tabela verdade original, apenas realiza alterações em uma cópia e a retorna no final.
    Funciona para qualquer tabela verdade (TruthTable) com n inputs (Matriz não precisa ser quadrada)

    Parâmetros
    ------------------------------------------------
    :param TruthTable: tabela verdade a ser analisada e transformada em modulação PAM
    :param epsilon: epsilon no qual os valores serão calculados
    
    Retorno
    ------------------------------------------------
    :return: retorna um numpy array como matriz da modulação PAM da tabela verdade recebida como parâmetro
    """
    if epsilon <= 0 or epsilon >= 1:
        raise ValueError(f'Epsilon must be major than 0 and minor than 1')
    PamTable = TruthTable.copy() # Como utiliza uma cópia, PamTable será uma matriz com elementos do tipo float
    rows, columns = PamTable.shape
    for row in range(rows):
        for column in range(columns):
            if PamTable[row][column] == 1:
                PamTable[row][column] = 1 + epsilon
            elif PamTable[row][column] == 0:
                PamTable[row][column] = 1 - epsilon
            else:
                raise ValueError('Truth Table must be filled just with zeros and ones')
    return PamTable

In [24]:
Inp = PAM(Table, 0.5)
print(f'INP: \n{Inp}\n\nTABELA VERDADE ORIGINAL: \n{Table}')

INP: 
[[0.5 0.5 0.5]
 [0.5 0.5 1.5]
 [0.5 1.5 0.5]
 [0.5 1.5 1.5]
 [1.5 0.5 0.5]
 [1.5 0.5 1.5]
 [1.5 1.5 0.5]
 [1.5 1.5 1.5]]

TABELA VERDADE ORIGINAL: 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [25]:
def InvPAM(PAMTable):
    """
    Função que retorna uma nova tabela verdade com modulação bniária (processo inverso da modulação PAM)
    
    Parâmetros
    ------------------------------
    :param PAMTable: Tabela verdade em modulação PAM (1 +- epsilon)
    
    Retorno
    ------------------------------
    :return: Retorna uma nova matriz como numpy array que representa a tabela verdade original (inversa da PAM)
    """
    rows, columns = PAMTable.shape
    ResultTable = np.ones(shape=(rows, columns), dtype=float)
    for row in range(rows):
        for column in range(columns):
            if PAMTable[row][column] < 1:
                ResultTable[row][column] = 0
    return ResultTable

In [26]:
InvPam = InvPAM(Inp)
print(f'Imp: \n\n{Inp}\nInvPAM: \n\n{InvPam}')

Imp: 

[[0.5 0.5 0.5]
 [0.5 0.5 1.5]
 [0.5 1.5 0.5]
 [0.5 1.5 1.5]
 [1.5 0.5 0.5]
 [1.5 0.5 1.5]
 [1.5 1.5 0.5]
 [1.5 1.5 1.5]]
InvPAM: 

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]


O único erro que a função PAM poderia dar era em retornar uma tabela verdade modulada erroneamente, o que não ocorre devido ao retorno da função $InvPAM$ ser exatamente igual à tabela verdade original. Assim, nenhum erro é cometido pelas funções.

A função $PAM$ e $InvPAM$ retornam numpy arrays (matrizes) do tipo float, logo lidam bem com quaisquer cálculos com números decimais.

## Geração de Tabelas Verdade Padrões (OR, AND)

Para dar continuidade à pesquisa, precisamos de uma função que nos retorne tabelas verdade de operadores lógicos padrões (OR, AND).

In [27]:
def OrTruthTableGenerator(TruthTable):
    """
    Retorna uma tabela verdade do circuito lógico OR de acordo com uma tabela verdade (TruthTable). 
    Checa se a tabela está vazia, se sim a retorna (vazia), se não, realiza os cálculos.
    
    Parâmetros
    ------------------------------------------------
    :param TruthTable: tabela verdade a ser analisada
    
    Retorno
    ------------------------------------------------
    :return: Retorna a coluna (numpy array) com os valores da tabela verdade OR dos inputs da tabela verdade recebida 
    como parâmetro
    """
    rows, columns = TruthTable.shape
    ResultTable = np.zeros(shape=(rows, 1), dtype=float)
    
    if TruthTable.size == 0:
        return TruthTable
    
    for row in range(rows):
        BooleanRowArray = TruthTable[row][:]
        if np.any(BooleanRowArray):
            ResultTable[row][0] = 1
        
    return ResultTable

In [28]:
def AndTruthTableGenerator(TruthTable):
    """
    Retorna uma tabela verdade do circuito lógico AND de acordo com uma tabela verdade (TruthTable). 
    Checa se a tabela está vazia, se sim a retorna (vazia), se não, realiza os cálculos.
    
    Parâmetros
    ------------------------------------------------
    :param TruthTable: tabela verdade a ser analisada
    
    Retorno
    ------------------------------------------------
    :return: Retorna a coluna (numpy array) com os valores da tabela verdade AND dos inputs da tabela verdade recebida 
    como parâmetro
    """
    rows, columns = TruthTable.shape
    ResultTable = np.zeros(shape=(rows, 1), dtype=float)
    
    if TruthTable.size == 0:
        return TruthTable
    
    for row in range(rows):
        BooleanRowArray = TruthTable[row][:]
        if np.all(BooleanRowArray):
            ResultTable[row][0] = 1;
    
    return ResultTable

In [29]:
OR = OrTruthTableGenerator(Table)
AND = AndTruthTableGenerator(Table)
print(f'OR TRUTH TABLE: \n{OR} \n\nAND TRUTH TABLE: \n{AND}')

OR TRUTH TABLE: 
[[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 

AND TRUTH TABLE: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]


Perceba que os exemplos utilizados para os cálculos das funções são feitos utilizando tabelas verdade de 3 inputs. No entanto, como já documentado, essas funções aceitam tabelas verdade de n inputs, sendo n um número natural.

Ambas as funções retornam valores de saída como dados do tipo float para realizar cálculos corretamente.

## Código de Teste

Os códigos abaixo realizam testes com as funções abordadas, seguindo o modelo (exemplo para o arranjo triangular):

$A = ArranjoT rinagular(α, β, γ) \newline T = MatrizTransferencia(A) \newline Inp = PAM(TV(3)) \newline Out = T Inp^{T} \newline Out = Out^{T} \newline OutPAM = PAM(OR)$

In [30]:
def ArranjoTriangular(alpha, beta, gama):
    A = np.array([[0, complex(0, gama), complex(0, beta)], 
                  [complex(0, gama), 0, complex(0, alpha)], 
                  [complex(0, beta), complex(0, alpha), 0]])
    return A

In [31]:
def MatrizTransferenciaTriangular(A, z):
    """
    Retorna a matriz de transferência triangular T a partir de uma matriz de arranjo triangular A a partir dos passos já citados
    Erro percentual de 10^(-14) a 10^(-16), ínfimo.
    
    Parâmetros
    --------------------------------------
    :param A: matriz de Arranjo Triangular como numpy array
    :param z: número real qualquer (comprimento do acoplador)
    
    Retorno
    
    :return:  matriz numpy array de transferência triangular T calculada com erro ínfimo.
    """
    eigvals, eigvecs = la.eig(A)
    D = np.array([[eigvals[0], 0, 0], 
                  [0, eigvals[1], 0], 
                  [0, 0, eigvals[2]]])
    P = eigvecs.copy()
    E = np.array([[np.exp(z*eigvals[0]), 0, 0], 
                  [0, np.exp(z*eigvals[1]), 0], 
                  [0, 0, np.exp(z*eigvals[2])]])
    
    if np.allclose(A, P @ D @ la.inv(P), atol=1e-17):
        raise ValueError(f'Parameter Matrix A has not property A == PDP^(-1) for a tolerance of {1e-17}')
    
    # T é a matriz de transferência
    T = P @ E @ la.inv(P)
    
    return T

In [32]:
A = ArranjoTriangular(1.2, 2.3, 3.4)
T = MatrizTransferenciaTriangular(A, 2)
Inp = PAM(Tv(3), 0.5)

Out = T @ Inp.T
Out = Out.T
OutPAM = PAM(OR, 0.5)

In [33]:
print(f'A: \n{A}\n\nT: \n{T}\n\nInp: \n{Inp}\n\nOut: \n{Out}\n\nOutPAM: \n{OutPAM}')

A: 
[[0.+0.j  0.+3.4j 0.+2.3j]
 [0.+3.4j 0.+0.j  0.+1.2j]
 [0.+2.3j 0.+1.2j 0.+0.j ]]

T: 
[[-0.11913715-0.47197274j -0.68805537+0.31241627j -0.36201378+0.246921j  ]
 [-0.68805537+0.31241627j -0.29909064-0.53387464j  0.07714144+0.22033551j]
 [-0.36201378+0.246921j    0.07714144+0.22033551j -0.59215774-0.63468631j]]

Inp: 
[[0.5 0.5 0.5]
 [0.5 0.5 1.5]
 [0.5 1.5 0.5]
 [0.5 1.5 1.5]
 [1.5 0.5 0.5]
 [1.5 0.5 1.5]
 [1.5 1.5 0.5]
 [1.5 1.5 1.5]]

Out: 
[[-0.58460315+4.36822673e-02j -0.45500228-5.61430694e-04j
  -0.43851504-8.37148968e-02j]
 [-0.94661693+2.90603272e-01j -0.37786084+2.19774082e-01j
  -1.03067278-7.18401208e-01j]
 [-1.27265852+3.56098532e-01j -0.75409292-5.34436070e-01j
  -0.36137359+1.36620616e-01j]
 [-1.6346723 +6.03019537e-01j -0.67695148-3.14100557e-01j
  -0.95353134-4.98065695e-01j]
 [-0.7037403 -4.28290468e-01j -1.14305766+3.11854834e-01j
  -0.80052881+1.63206108e-01j]
 [-1.06575408-1.81369463e-01j -1.06591622+5.32190347e-01j
  -1.39268655-4.71480203e-01j]
 [-1.39179568-

## Testes

### 1) A modulação PAM e a função InvPAM funcionam corretamente? (SIM)

In [34]:
Original = Tv(3)
InpTeste = PAM(Original, 0.5)
RetornoInv = InvPAM(InpTeste)
print(f'Original: \n\n{Original}\nINP: \n\n{InpTeste}\n\nRetorno InvPAM: \n\n{RetornoInv}')
print(np.allclose(Original, RetornoInv))

Original: 

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
INP: 

[[0.5 0.5 0.5]
 [0.5 0.5 1.5]
 [0.5 1.5 0.5]
 [0.5 1.5 1.5]
 [1.5 0.5 0.5]
 [1.5 0.5 1.5]
 [1.5 1.5 0.5]
 [1.5 1.5 1.5]]

Retorno InvPAM: 

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
True


### 2) O cálculo de Out functiona corretamente? Análise do erro (SIM)

Para o cálculo do erro da matriz $Out$, faremos manipulações de matrizes assim como fizemos com a matriz $E$ no estágio da semana anterior. Seja $Out = T Inp^T$. Podemos comparar visualmente as duas matrizes, ou podemos utilizar o método ``np.allclose(atol=1e-18)``, na qual atol é uma tolerância ínfima, quase nula, mas mesmo assim vemos que a função retorna True.

Ou seja, os cálculos são feitos de maneira correta.

In [35]:
print(f'out: \n\n{Out.T}\n\nT @ Inp.T: \n\n{T @ Inp.T}')

out: 

[[-0.58460315+4.36822673e-02j -0.94661693+2.90603272e-01j
  -1.27265852+3.56098532e-01j -1.6346723 +6.03019537e-01j
  -0.7037403 -4.28290468e-01j -1.06575408-1.81369463e-01j
  -1.39179568-1.15874203e-01j -1.75380945+1.31046802e-01j]
 [-0.45500228-5.61430694e-04j -0.37786084+2.19774082e-01j
  -0.75409292-5.34436070e-01j -0.67695148-3.14100557e-01j
  -1.14305766+3.11854834e-01j -1.06591622+5.32190347e-01j
  -1.4421483 -2.22019804e-01j -1.36500685-1.68429208e-03j]
 [-0.43851504-8.37148968e-02j -1.03067278-7.18401208e-01j
  -0.36137359+1.36620616e-01j -0.95353134-4.98065695e-01j
  -0.80052881+1.63206108e-01j -1.39268655-4.71480203e-01j
  -0.72338737+3.83541620e-01j -1.31554511-2.51144690e-01j]]

T @ Inp.T: 

[[-0.58460315+4.36822673e-02j -0.94661693+2.90603272e-01j
  -1.27265852+3.56098532e-01j -1.6346723 +6.03019537e-01j
  -0.7037403 -4.28290468e-01j -1.06575408-1.81369463e-01j
  -1.39179568-1.15874203e-01j -1.75380945+1.31046802e-01j]
 [-0.45500228-5.61430694e-04j -0.37786084+2.19

In [36]:
np.allclose(Out.T, T @ Inp.T, atol=1e-18)

True